---
title: "R_packages"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Useful R packages

```{r must_install}
install.packages("devtools")
install.packages("ggplot2")
install.packages("dplyr")
install.packages(c("devtools", "roxygen2", "testthat", "knitr"))
install.packages("tidyr")
install.packages("magrittr")
install.packages("reshape2")
install.packages("stringr")
install.packages("lubridate")
install.packages("shiny")
install.packages("forcats")
install.packages("htmlwidgets")
install.packages("leaflet")
install.packages("Rcpp")
install.packages("data.table")
install.packages("broom")
install.packages("RColorBrewer")
install.packages("qtl")


## Bioconductor packages
source("https://bioconductor.org/biocLite.R")
biocLite("org.Mm.eg.db")
biocLite("GenomicRanges")
biocLite("qvalue")
biocLite("sva")
biocLite("DESeq2")
biocLite("pathview")
biocLite("gage")
biocLite("gageData")
biocLite("pheatmap")
biocLite("limma")
biocLite("edgeR")
biocLite("SummarizedExperiment")
biocLite("topGO")
library(devtools)
install_github("satijalab/seurat")
```

